### ISSUE TITLE
Using this addon inside of an engine causes Route to be reopened twice

### ISSUE THREAD

**Issue by HeroicEric** [offirgolan/ember-parachute#39]
When this addon is used inside of an engine, it's initializer is run twice, once for the parent app and once for the engine. This results in all of the hooks being fired twice.

For example, the `queryParamsDidChange` hook will run twice every time a query param changes.

I can create a demo app if you'd like.

**Comment by offirgolan** [comment]
That makes sense. @HeroicEric I'll investigate further. PR is always welcome 😄
