### ISSUE TITLE
Provide a way to get serialized QPs from the controller

### ISSUE THREAD

**Issue by anehx** [offirgolan/ember-parachute#41]
Hi,

First of all, thanks for creating and maintaining this awesome addon! :+1: 

It would be awesome if you could provide a way to access the serialized query params from the controller. This way I wouldn't have to serialize them manually when I fetch the data..

I'd be glad to help with this, just let me know if you think it is a good idea.

**Comment by offirgolan** [comment]
@anehx I'm not sure what you mean by this. Can you elaborate?

**Comment by anehx** [comment]
Let's assume we have a QP object like this:
```javascript
const myQueryParams = new QueryParams({
  someDate: {
    defaultValue: null,
    as: 'some_date',
    serialize(m) {
      return m && m.format('YYYY-MM-DD')
    },
    deserialize(s) {
      return s && moment(s, 'YYYY-MM-DD')
    }
  }
})
```
If I set `someDate` to some value, the URL will update to `...?some_date=2017-10-20` but the value of `someDate` on the controller will be the moment object. If I want to use the query params now to fetch my data in the controller I can't just take the URL query params or did I miss something?

What I want is to access `some_date` with the value `2017-10-20` from the controller.

**Comment by poteto** [comment]
The `deserialize` function you provide in the QP map will let you do exactly that.

**Comment by poteto** [comment]
It sounds like you don't need to provide `serialize/deserialize`.

**Comment by poteto** [comment]
The value of `someDate` is a moment object because that's how you're deserializing it. You can either deserialize it into the type you want, or just remove the `serialize` and `deserialize` functions.

**Comment by anehx** [comment]
Sure I could just make keep it a string but I need the QP to be a moment object. It is absolutely logical that `someDate` is a moment object than. What I'm trying to say is that it'd be nice if I could get the serialized version (which is used in the URL) too.

**Comment by offirgolan** [comment]
You can get the value you want via the [allQueryParams](https://github.com/offirgolan/ember-parachute#computed-property---allqueryparams) property on the controller. 

```
this.get('allQueryParams.someDate') === '2017-10-20'
this.get('someDate') === moment(...)
```

**Comment by offirgolan** [comment]
Actually I lied, those values are not serialized.

**Comment by anehx** [comment]
Yeah I just tried that.. But I wouldn't expect them to be serialized. But I think it'd be useful to have something like `allSerializiedQueryParams` or something like that. Do you agree?

**Comment by mazondo** [comment]
This request didn't make sense to me when I read it first, but here we are, 2 days into using ember-parachute, wishing it existed 😂

**Comment by knownasilya** [comment]
Looks like this can be closed.
