### ISSUE TITLE
Accessing the controller / services

### ISSUE THREAD

**Issue by buschtoens** [offirgolan/ember-parachute#46]
Would it hurt, if we were able to access the corresponding `Controller` from the `serialize` and `deserialize` methods?

I am asking primarily because I need to *synchronously* access the `store` service, in order to lookup a record for an ID. Basically something like this:

```js
new QueryParams({
  someModel: {
    defaultValue: null,

    serialize(model) {
      return model ? get(model, 'id') : '';
    },

    deserialize(id) {
      return id ? get(this, 'store').peekRecord('model-name', id) : null;
    }
});
```
Do you think this is a form of unhealthy entanglement, even though the lookup is guaranteed to work synchronously?

**Comment by offirgolan** [comment]
@buschtoens I think thats a pretty valid use-case and can be easily done by passing the controller to those methods [here](https://github.com/offirgolan/ember-parachute/blob/master/addon/initializers/ember-parachute.js#L91) and [here](https://github.com/offirgolan/ember-parachute/blob/master/addon/initializers/ember-parachute.js#L114).

The only concern that I have is that when the app boots, if the controller is not yet ready we use the proto to access some methods / attributes. At that point, I'm not really sure if you will have access to the store or any other service tbh. I think this is something that should be pretty well tested.

PR is welcome!

/cc @poteto

**Comment by Techn1x** [comment]
+1!

Seems like a very common use case - having a record ID (or array of them) in the URL, then wanting to easily retrieve those records

**Comment by Techn1x** [comment]
I gave this a quick go by passing in the controller to both methods as suggested above, and it seems like the controller isn't always ready and when it's not, there's no access to the store.

Any other alternatives?

**Comment by buschtoens** [comment]
@poteto Absolutely. How would you like the controller to be passed? As a a second param directly or wrapped in an object, so that it's easier to add additional props in the future?

```js
new QueryParams({
  someModel: {
    defaultValue: null,

    serialize(model, controller) {
      return model ? get(controller, 'id') : '';
    },

    deserialize(id, controller) {
      return id ? get(controller, 'store').peekRecord('model-name', id) : null;
    }
});
```
```js
new QueryParams({
  someModel: {
    defaultValue: null,

    serialize(model, { controller }) {
      return model ? get(controller, 'id') : '';
    },

    deserialize(id, { controller }) {
      return id ? get(controller, 'store').peekRecord('model-name', id) : null;
    }
});
```

**Comment by poteto** [comment]
First option looks good!

**Comment by buschtoens** [comment]
Cool! 

@Techn1x Do you want to land a PR? 😉
If not I'll get around to it next week.

**Comment by Techn1x** [comment]
I'll see if I can find the time this week

**Comment by evoactivity** [comment]
I don't seem to be able to access the store at all.

I get an `Assertion Failed: Attempting to lookup an injected property on an object without a container, ensure that the object was instantiated via a container.` error on `get(controller, 'store')` .

@buschtoens I assume your PR worked for your use case or did you need to do anything else to actually access the store?

**Comment by evoactivity** [comment]
EmberTwiddle is currently getting a CORS error when I try to install the addon, so can't setup a demo right now.

Doing `get(controller, 'someOtherProperty')` works if it's just a normal property on the controller, it's only when I try to get a service.

this is my parameter

```javascript
selectedQualifications: {
    as: 'qualifications',
    defaultValue: [],
    serialize(records) {
      let ids = records.map((record) => {
        return get(record, 'id');
      });
      return ids.toString();
    },
    deserialize(ids = '', controller) {
      let records = [];
      ids.split(',').forEach((id) => {
        let record = get(controller, 'store').peekRecord('course', id);
        records.addObject(record);
      });

      return records;
    }
  }
```

If the page loads without the query parameter set it seems to work (because it's not trying to deserialize it I suppose), if the parameters are set when the page loads then it errors.

This is on ember 2.18 (same for ember-data).

**Comment by roberkules** [comment]
I have the same issue

> "Assertion Failed: Attempting to lookup an injected property on an object without a container, ensure that the object was instantiated via a container."

pretty much same same code:

```javascript
deserialize(value = '', controller) {
  let store = get(controller, 'store');  // <== FAILS HERE
  return value.split(',').map(id => store.peekRecord('location', id));
}
```

**Comment by offirgolan** [comment]
> Assertion Failed: Attempting to lookup an injected property on an object without a container, ensure that the object was instantiated via a container. error on get(controller, 'store')

This is stating that the controller has not yet been initialized with the container necessary for you to access the store (or any other service). This is the one caveat with this implementation in that `serialize` and `deserialize` can be called before the controller is actually ready. Unfortunately, this isn't something that can be fixed from this addon.

**Comment by roberkules** [comment]
@offirgolan @buschtoens so how would you deal with scenarios where you have a record/recordarray that needs to be persisted to the url? any advice?

**Comment by evoactivity** [comment]
@roberkules I'm going to try an aproach today using a computed property which is the actual records array with the url parameters just being an array of ids, when that array updates the computed property should recompute a corresponding array.

@offirgolan @buschtoens would you say that sounds like a reasonable way to implement this functionality?

**Comment by Techn1x** [comment]
Thanks @evoactivity I also added `queryParamsDidChange` so that even if the ID in the URL is changed later, those changes will be shown

```javascript
export const validQueryParams = new QueryParams({
  selectedAssetId: {
    as: 'asset',
    defaultValue: ''
  }
});
```

```javascript
// Set initial selectedAsset from ID in URL
setup({ queryParams }) {
  if(queryParams.selectedAssetId) {
    this.store.findRecord('asset',queryParams.selectedAssetId).then((asset) => {
      this.set('selectedAsset',asset));
    }
  }
},

// If ID in URL changes, update the selectedAsset
queryParamsDidChange({ shouldRefresh, queryParams, changed, changes }) {
  if(queryParams.selectedAssetId !== this.get('selectedAsset.id')) {
    if(queryParams.selectedAssetId) {
      this.store.findRecord('asset',queryParams.selectedAssetId).then((asset) => {
        this.set('selectedAsset',asset));
      }
    } else {
      if(this.get('selectedAsset')) this.set('selectedAsset',undefined);
    }
  }
},

actions: {
  // Use this action from the template to set a new asset, so that both properties are modified
  selectAsset(asset) {
    this.set('selectedAsset',asset);	// Set the selectedAsset to use
    this.set('selectedAssetId', asset ? asset.get('id') : '');	// Set the asset ID in the URL
  }
}
```
