### ISSUE TITLE
Preventing a query param change

### ISSUE THREAD

**Issue by alexlafroscia** [offirgolan/ember-parachute#49]
What do you think about adding a way to prevent a query param from changing? In a use case where you might bind a tab-like interface to a query param, with the active tab in the URL. With a normal route-driven UI, you could hook into `willTransition` to prevent a transition, but there's no way to have similar behavior with Parachute. Supporting `refreshModel` would solve this specific use case, but [I know that that's not going to be supported](https://github.com/offirgolan/ember-parachute/pull/32).

I'm imagining something like `queryParamsWillChange` that could return `false` to reject the change

**Comment by offirgolan** [comment]
I think its something that we can work towards supporting. Instead of fully supporting `refreshModel` we can have an option such as `locked` and we can do all the work to support something like that (just brainstorming) via the controller and route mixins.

**Comment by offirgolan** [comment]
Now that I think of it, maybe it would be a good idea to pass through `refreshModel` but just add some documentation around it. This addon really shouldnt be limiting the functionality of query params, but just improving on it. 

@poteto thoughts?

**Comment by alexlafroscia** [comment]
I can't even remember why I wanted this anymore 🤷‍♂️
