### ISSUE TITLE
I'm an idiot - can you link code for the example

### ISSUE THREAD

**Issue by jalligator** [offirgolan/ember-parachute#63]
This project is exactly what I'm looking for, but for the life of me I can't figure out how to bind input values to the query parameters. I'd love a look at the parachute demo!

**Comment by scottwernervt** [comment]
The code for the demo is the dummy testing app: https://github.com/offirgolan/ember-parachute/blob/master/tests/dummy/app/.

**Comment by jalligator** [comment]
So the answer to my idiot question is in the dummy app? Figures :-P

I get the Mixin property for the controller, but there’s no way to automagically pass the lot of parameters to a component? Do I just pass the controller itself down the hierarchy? I’ve got gobs of tables and the columns are filterable. I’d like to give each column a qp key and, from what I can tell, the controller to have the columnar component set the value for the column’s corresponding qp value. The way I have it now, I end up having to bind each column’s filter field individually to its corresponding qp value via component bindings. So if I have 8 columns and they’re all filterable by ranges, I end up with 16 bindings. This causes me to want to kill myself - in contrast to the project goal.

**Comment by jalligator** [comment]
Never mind. I did a bunch of reading and get it now. Thanks.

**Comment by jalligator** [comment]
I should have mentioned that @poteto’s writeup on skeleton loading was of great help in getting my head around this issue. Also, in the research of my use-case, URLSearchParams was a huge help. Browser compatibility isn’t a huge problem for me and polyfills are readily available even if it was. It totally flies in the face of the Ember way of handling qps, but it has allowed me to very easily abandon the controller and route busywork of managing qps and move model loading entirely to components while managing state entirely though qps. Very nice!
