### ISSUE TITLE
NAME_KEY is deprecated

### ISSUE THREAD

**Issue by efx** [offirgolan/ember-parachute#72]
As of https://github.com/emberjs/ember.js/pull/16710, 
[`NAME_KEY`](https://github.com/offirgolan/ember-parachute/blob/master/addon/query-params.js#L11) is deprecated. I think we just need to override the `toString` method on the controller mixin.

**Comment by scottkidder** [comment]
Thanks @efx! :tada: Looks to be resolved on master. Would be great to have a release cut to kill the deprecation noise.

**Comment by offirgolan** [comment]
Released under `v1.0.1` 😄
